services:
  user_service_james:
    build: ./user_service_james
    ports: ["5101:5101"]

  cart_service:
    build: ./cart_service
    ports: ["5102:5102"]

  inventory_service:
    build: ./inventory_service
    ports: ["5103:5103"]

  payment_service:
    build: ./payment_service
    ports: ["5104:5104"]

  invoice_service:
    build: ./invoice_service
    ports: ["5105:5105"]

  shipping_service:
    build: ./shipping_service
    ports: ["5106:5106"]

  notification_service:
    build: ./notification_service
    ports: ["5107:5107"]

  analytics_service:
    build: ./analytics_service
    ports: ["5108:5108"]

  loyalty_service:
    build: ./loyalty_service
    ports: ["5109:5109"]

  review_service:
    build: ./review_service
    ports: ["5110:5110"]

  orchestrator:
    build: ./orchestrator
    ports: ["5100:5100"]
    depends_on:
      - user_service_james
      - cart_service
      - inventory_service
      - payment_service
      - invoice_service
      - shipping_service
      - notification_service
      - analytics_service
      - loyalty_service
      - review_service

