apiVersion: apps/v1
kind: Deployment
metadata:
  name: wand-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wand-service
  template:
    metadata:
      labels:
        app: wand-service
    spec:
      containers: 
      - name: wand-service
        image: wand-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wand-service
spec:
  selector:
    app: wand-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP